/* automatically generated by rust-bindgen 0.57.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CFlouiViewController {
    _unused: [u8; 0],
}
extern "C" {
    pub fn CFlouiViewController_new(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *mut ::std::os::raw::c_void,
        arg3: *mut ::std::os::raw::c_void,
    ) -> *mut CFlouiViewController;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CWidget {
    _unused: [u8; 0],
}
pub type CFlouiCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut CWidget, data: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CMainView {
    _unused: [u8; 0],
}
extern "C" {
    pub fn CMainView_new(fvc: *const CFlouiViewController) -> *mut CMainView;
}
extern "C" {
    pub fn CMainView_add(self_: *mut CMainView, w: *const CWidget);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CButton {
    _unused: [u8; 0],
}
extern "C" {
    pub fn CButton_new(label: *const ::std::os::raw::c_char) -> *mut CButton;
}
extern "C" {
    pub fn CButton_action(
        self_: *mut CButton,
        cb: CFlouiCallback,
        data: *mut ::std::os::raw::c_void,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CText {
    _unused: [u8; 0],
}
extern "C" {
    pub fn CText_new(label: *const ::std::os::raw::c_char) -> *mut CText;
}
extern "C" {
    pub fn CText_text(self_: *mut CText, t: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn Cfloui_log(s: *const ::std::os::raw::c_char);
}
